"""
build_registry.py
-----------------
Auto-generates player_registry.py from the FC26 stats CSV.
Ensures ALL 32 FIFA WC 2022 teams (including Austria, Ecuador, Senegal) have
fully populated rosters of 26 players, using club_jersey_number as a fallback
when nation_jersey_number is missing.
"""

import sys, os
sys.stdout.reconfigure(encoding='utf-8')
import pandas as pd

STATS_CSV = os.environ.get("STATS_CSV_PATH", r"C:\Users\sande\Downloads\stat\FC26_20250921.csv")
if not os.path.exists(STATS_CSV):
    # Try local datasets folder fallback
    STATS_CSV = os.path.abspath("datasets/stat/FC26_20250921.csv")

OUTPUT_FILE = os.path.abspath("player_registry.py")

# FIFA 2022 World Cup teams (all 32)
WC2022_TEAMS = [
    'Argentina', 'Australia', 'Belgium', 'Brazil', 'Cameroon', 'Canada',
    'Costa Rica', 'Croatia', 'Denmark', 'Ecuador', 'England', 'France',
    'Germany', 'Ghana', 'Iran', 'Japan', 'Mexico', 'Morocco', 'Netherlands',
    'Poland', 'Portugal', 'Qatar', 'Saudi Arabia', 'Senegal', 'Serbia',
    'South Korea', 'Spain', 'Switzerland', 'Tunisia', 'United States',
    'Uruguay', 'Wales', 'Austria'  # Added Austria as it is in the highlight video
]

def clean_name(name: str) -> str:
    """Remove accents and special chars that break the Python source."""
    import unicodedata
    nfkd = unicodedata.normalize('NFKD', str(name))
    return ''.join(c for c in nfkd if not unicodedata.combining(c)).strip()

def main():
    print(f"[Registry Builder] Loading stats CSV: {STATS_CSV}")
    if not os.path.exists(STATS_CSV):
        print(f"[Registry Builder] ERROR: Stats CSV not found at {STATS_CSV}")
        sys.exit(1)

    df = pd.read_csv(STATS_CSV, low_memory=False)
    print(f"[Registry Builder] Total players: {len(df)}")

    registry: dict[str, dict[int, str]] = {}

    for team in WC2022_TEAMS:
        team_key = team.lower()
        # Filter all players of this nationality
        team_players = df[df['nationality_name'] == team].copy()
        if len(team_players) == 0:
            print(f"[Registry Builder] Warning: no players found for nationality {team}")
            continue

        # Sort by overall rating to get the best 26 players
        team_players = team_players.sort_values(by='overall', ascending=False).head(26)

        squad = {}
        used_numbers = set()

        # Step 1: Assign populated jersey numbers
        for _, row in team_players.iterrows():
            name = clean_name(row['short_name'])
            
            # Determine best jersey number: nation_jersey_number -> club_jersey_number
            jersey = None
            if pd.notna(row.get('nation_jersey_number')):
                jersey = int(row['nation_jersey_number'])
            elif pd.notna(row.get('club_jersey_number')):
                jersey = int(row['club_jersey_number'])
                
            if jersey is not None and 1 <= jersey <= 99 and jersey not in used_numbers:
                squad[jersey] = name
                used_numbers.add(jersey)

        # Step 2: Fill in missing numbers for any players without a unique number
        fallback_num = 1
        for _, row in team_players.iterrows():
            name = clean_name(row['short_name'])
            if name in squad.values():
                continue
                
            while fallback_num in used_numbers:
                fallback_num += 1
            squad[fallback_num] = name
            used_numbers.add(fallback_num)
            fallback_num += 1

        registry[team_key] = squad

    # Write the generated file
    lines = [
        '"""',
        'player_registry.py  [AUTO-GENERATED by build_registry.py]',
        'FIFA WC 2022 — maps nationality (lowercase) -> jersey number -> player short name.',
        '"""',
        '',
        'SQUAD_DB: dict[str, dict[int, str]] = {',
    ]

    for team in sorted(registry.keys()):
        squad = registry[team]
        if not squad:
            continue
        lines.append(f'    "{team}": {{')
        for jersey in sorted(squad.keys()):
            player = squad[jersey].replace('"', '\\"')
            lines.append(f'        {jersey}: "{player}",')
        lines.append('    },')
        lines.append('')

    lines += [
        '}',
        '',
        '# ----- Name → jersey reverse lookup -----',
        '_NAME_TO_JERSEY: dict[str, dict[str, int]] = {}',
        'for _t, _squad in SQUAD_DB.items():',
        '    _NAME_TO_JERSEY[_t] = {v.lower(): k for k, v in _squad.items()}',
        '',
        '',
        'def get_player_name(team_name: str, jersey_number: int) -> str | None:',
        '    """Return short name for a given team + jersey number, or None if not found."""',
        '    if not team_name:',
        '        return None',
        '    squad = SQUAD_DB.get(team_name.strip().lower(), {})',
        '    return squad.get(int(jersey_number))',
        '',
        '',
        'def get_jersey_number(team_name: str, player_name: str) -> int | None:',
        '    """Reverse lookup: player name -> jersey number."""',
        '    reverse = _NAME_TO_JERSEY.get(team_name.strip().lower(), {})',
        '    return reverse.get(player_name.strip().lower())',
        '',
        '',
        'def get_all_team_names() -> list[str]:',
        '    """Return sorted list of all known team names (title case)."""',
        '    return sorted(t.title() for t in SQUAD_DB)',
        '',
        '',
        'def get_squad(team_name: str) -> dict[int, str]:',
        '    """Return full squad dict for a team. Empty if unknown."""',
        '    return SQUAD_DB.get(team_name.strip().lower(), {})',
    ]

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')

    print(f"\n[Registry Builder] SUCCESS — wrote {OUTPUT_FILE}")
    print(f"  Teams: {len(registry)}")
    print(f"  Total jersey→name entries: {sum(len(v) for v in registry.values())}")

if __name__ == "__main__":
    main()
